DESIRED_CAPABILITIES = {
    "appium:deviceName": "Pixel",
    "platformName": "Android",
    "appium:appPackage": "ru.spbstu.payshare",
    "appium:app": "/home/runner/work/PayShare/PayShare/apk/app-debug.apk",
    "appium:appWaitActivity": "ru.spbstu.payshare.root.presentation.RootActivity"
}

WEB_ADDRESS = "http://localhost:4723/wd/hub"

locators = {
    "vk_auth": "ru.spbstu.payshare:id/frg_login__mb_vk",
    "google_auth": "ru.spbstu.payshare:id/frg_login__mb_google",
    "profile_button": "ru.spbstu.payshare:id/profileFragment",
    "opened_rooms_button": "ru.spbstu.payshare:id/eventsFragment",
    "archive_button": "ru.spbstu.payshare:id/historyFragment",
    "rooms_cards": "ru.spbstu.payshare:id/item_events__card_view",
    "rooms_cards_titles": "ru.spbstu.payshare:id/item_events__tv_event_title",
    "profile_name": "ru.spbstu.payshare:id/frg_profile__tv_name",
    "page_title": "ru.spbstu.payshare:id/include_toolbar__tv_title",
    "event_dialog_title": "ru.spbstu.payshare:id/frg_add_event_dialog__tv_title",
    "first_toolbar_button": "ru.spbstu.payshare:id/include_toolbar__ib_first_button",
    "second_toolbar_button": "ru.spbstu.payshare:id/include_toolbar__ib_second_button",
    "back_toolbar_button": "ru.spbstu.payshare:id/include_toolbar__ib_back_button",
    "code_text": "ru.spbstu.payshare:id/frg_search_event_dialog__pin_field",
    "code_ok_button": "ru.spbstu.payshare:id/frg_serch_event_dialog__mb_ok",
    "code_window_title": "ru.spbstu.payshare:id/frg_search_event_dialog__tv_title",
    "add_float_button": "ru.spbstu.payshare:id/frg_events__fab_add",
    "add_float_button_room": "ru.spbstu.payshare:id/frg_event__fab_add",
    "edit_float_button": "ru.spbstu.payshare:id/frg_event__fab_edit",
    "save_room_button": "ru.spbstu.payshare:id/frg_add_event_dialog__mb_save",
    "add_room_name": "ru.spbstu.payshare:id/frg_add_event_dialog__et_title",
    "add_room_date": "ru.spbstu.payshare:id/frg_add_event_dialog__et_date",
    "add_room_time": "ru.spbstu.payshare:id/frg_add_event_dialog__et_time",
    "total_amount": "ru.spbstu.payshare:id/item_events__tv_total_amount",
    "share_code": "ru.spbstu.payshare:id/frg_qr_code_sharing__tv_code",
    "add_purchase_title": "ru.spbstu.payshare:id/frg_add_purchase_dialog__tv_title",
    "add_purchase_name": "ru.spbstu.payshare:id/frg_add_purchase_dialog__et_title",
    "add_purchase_cost": "ru.spbstu.payshare:id/frg_add_purchase_dialog__et_price",
    "add_purchase_date": "ru.spbstu.payshare:id/frg_add_purchase_dialog__et_date",
    "add_purchase_shop": "ru.spbstu.payshare:id/frg_add_purchase_dialog__et_shop",
    "add_shop_title": "ru.spbstu.payshare:id/frg_shop_map_dialog__et_title",
    "add_shop_save_button": "ru.spbstu.payshare:id/frg_shop_map_dialog__mb_done",
    "add_purchase_save_button": "ru.spbstu.payshare:id/frg_add_purchase_dialog__mb_save",
    "delete_dialog": "ru.spbstu.payshare:id/frg_delete_dialog__text",
    "delete_dialog_ok": "ru.spbstu.payshare:id/frg_delete_dialog__mb_ok",
    "delete_dialog_cancel": "ru.spbstu.payshare:id/frg_delete_dialog__mb_cancel",
    "purchase": "ru.spbstu.payshare:id/item_purchase__layout",
    "purchase_is_bought": "ru.spbstu.payshare:id/item_purchase__cb_is_bought",
    "purchase_name": "ru.spbstu.payshare:id/item_purchase__tv_description",
    "purchase_date": "ru.spbstu.payshare:id/item_purchase__tv_date",
    "purchase_price": "ru.spbstu.payshare:id/item_purchase__price",
    "purchase_info_button": "ru.spbstu.payshare:id/dialog_purchase_options__tb_ib_info",
    "purchase_delete_button": "ru.spbstu.payshare:id/dialog_purchase_options__tb_delete_file",
    "purchase_info_name": "ru.spbstu.payshare:id/item_purchase_info__tv_description",
    "purchase_info_buyer": "ru.spbstu.payshare:id/item_purchase_info__tv_buyer_name",
    "purchase_info_date": "ru.spbstu.payshare:id/item_purchase_info__tv_date",
    "purchase_info_price": "ru.spbstu.payshare:id/item_purchase_info__price",
    "purchase_info_participants": "ru.spbstu.payshare:id/item_user__iv",

}
