name: Android CI

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  apk:
    name: Generate APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build APK
        run: bash ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v1
        with:
          name: apk
          path: app/build/outputs/apk/debug/app-debug.apk 
  check_apk:
    name: Check APK
    needs: apk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Download APK from build
        uses: actions/download-artifact@v1
        with:
          name: apk
      - name: Appium Server Action
        uses: moatazeldebsy/Appium-Server-GitHub-Action@V1.0.5
      - name: Install python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.8
      - name: PIP install
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            requests
            pytest_check
            loguru
            pytest-html
            Appium-Python-Client
      - name: Setup Android SDK Tools
        uses: android-actions/setup-android@v2.0.2
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.23.0
        with:
          api-level: 23
          # hardware profile used for creating the AVD - e.g. `Nexus 6`
          profile: Nexus 6
      - name: Test
        run: python3 -m pytest tests/ui -v --html=report.html --device_name="NEXUS 6" --web_address=http://localhost:4723 --app apk/app-debug.apk
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.html
            
        
