name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
  
jobs:
  check_apk:
    name: Check APK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install python
        uses: actions/setup-python@v3.0.0
        with:
          python-version: 3.8
      - name: PIP install
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            requests
            pytest_check
            loguru
            pytest-html
            Appium-Python-Client
      - name: Test
        run: python3 -m pytest tests/ui --web_address="https://bsuser_WTXaQD:VSfBwp1ma1B8X9VCykMG@hub-cloud.browserstack.com/wd/hub" --device_name="Samsung Galaxy S8 Plus" --app="bs://4541e9baf57e85aba43755597c2369cb5f1c0471" -v --html=report.html
      - name: Upload report
        uses: actions/upload-artifact@v1
        with:
          name: report
          path: report.html
